<?php
/** 
 * Implements hook_entity_info_alter().
 */
function openpolicy_theme_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['grid'] = array(
    'label' => t('Grid'),
    'custom settings' => FALSE,
  );

  $entity_info['node']['view modes']['featured'] = array(
    'label' => t('Featured'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_preprocess_node().
 */
function openpolicy_theme_preprocess_node(&$vars) {
  switch ($vars['view_mode']) {
    case 'grid':
      $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__grid';
      break;

    case 'featured':
      $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__featured';
      break;
  }
}
