<?php
/**
 * Implementation of hook_ctools_plugin_directory()
 */
function openpolicy_slideshow_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/** 
 * Implementation of hook_entity_info_alter()
 */
function openpolicy_slideshow_entity_info_alter(&$entity_info) {

  $entity_info['fieldable_panels_pane']['bundles']['slideshow'] = array(
    'label' => t('Add slideshow'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'openpolicy_slideshow') . '/images/icon_slideshow.png',
    'admin' => array(
      'path' => 'admin/structure/panels/entity/manage/%fieldable_panels_panes_type',
      'bundle argument' => 5,
      'real path' => 'admin/structure/panels/entity/manage/slideshow',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
